#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI2 -d 1 2 3 
bspc monitor eDP1 -d 4 5 6 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc rule -a gimp desktop='^3' state=floating follow=on
bspc rule -a firefox desktop='^1' follow=on focus=on

bspc config focused_border_color	"#BD93F9"
bspc config normal_border_color		"#282A36"
bspc config active_border_color		"#8BE9FD"
bspc config presel_feedback_color	"#50FA7B"

xsetroot -cursor_name left_ptr
