vo=gpu-next
gpu-api=vulkan
hwdec=vulkan-copy
profile=gpu-hq
scale=ewa_lanczossharp
cscale=mitchell
deband=yes
sub-auto=fuzzy
sub-font-size=44
sub-border-size=2
sub-shadow-offset=1
sub-color='#FFFFFFFF'
save-position-on-quit=yes
slang=hrv,hr,en,eng
alang=hrv,hr,en,eng
