music_directory    "~/Music"
playlist_directory "~/.local/share/mpd/playlists"
db_file            "~/.local/share/mpd/mpd.db"
log_file           "~/.local/share/mpd/mpd.log"
state_file         "~/.local/share/mpd/mpd.state"
sticker_file       "~/.local/share/mpd/sticker.sql"

bind_to_address    "127.0.0.1"
port               "6600"
auto_update        "yes"

audio_output {
        type            "alsa"
        name            "iFi ZEN Air DAC"
        device          "hw:Audio,0"         
        mixer_type      "none"            
        dsd_usb         "yes"            
        dsd_native      "yes"            
}

audio_output {
        type            "pulse"
        name            "EMBERTON II"
        device          "bluez_output.50_5E_5C_2F_19_9C.1"         
        mixer_type      "none"            
        dsd_usb         "yes"            
        dsd_native      "yes"            
}

audio_output {
    type                "fifo"
    name                "my_fifo"
    path                "/tmp/mpd.fifo"
    format              "44100:16:2"
}
