#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI2 -d 1 2 3 
bspc monitor eDP1 -d 4 5 6 

bspc config border_width	2
bspc config window_gap		0	

bspc config split_ratio			0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true
bspc config click_to_focus              true
bspc config focus_by_distance           true
bspc config history_aware_focus         true
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors	true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc rule -a gimp desktop='^3' state=floating follow=on
bspc rule -a firefox desktop='^1' follow=on focus=on

bspc config normal_border_color		"#44475a"
bspc config active_border_color 	"#6272a4"
bspc config focused_border_color 	"#ff3cff"
bspc config presel_feedback_color 	"#6272a4"

xsetroot -cursor_name left_ptr
