#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr

bspc monitor HDMI2 -d 1 2 3
bspc monitor eDP1  -d 4 5 6

bspc config border_width	1
bspc config window_gap		0

bspc config split_ratio			0.52
bspc config single_monocle		true
bspc config borderless_monocle   	true	
bspc config gapless_monocle      	true
bspc config pointer_follows_focus 	true
bspc config focus_follows_pointer	true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a Steam desktop='^3' follow=on focus=on
bspc rule -a Lutris desktop='^3' follow=on focus=on

bspc config normal_border_color   "#44475a"
bspc config active_border_color   "#bd93f9"
bspc config focused_border_color  "#ff79c6"
bspc config presel_feedback_color "#6272a4"
